#define LOC_NOTPROPERAPP    " is not a proper .APP file"
#define LOC_ISCRYPTED       " is a crypted .APP file"
#define LOC_NOTSTANDARDAPP  " is not a standard .APP file"
#define LOC_NOTANEXEFILE    " is not an exe file"
#define LOC_NOTANEXEFILE32  " is not a Win32 exe file"
#define LOC_NOTAFOXPROEXE   " is not an exe file created by Microsoft Visual FoxPro"
#define LOC_ALREADYEXISTS   " already exists"
#define LOC_NOTVISUALFOXPRO " is not a visual FoxPro production"
#define LOC_APPNOTFOUNDINEXE " App not found in exe file"